-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 31d977474835db613390701eb0c68abbc3814438
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
