Amazon_SWF_APIs:
    - CountClosedWorkflowExecutions
    - CountOpenWorkflowExecutions
    - CountPendingActivityTasks
    - CountPendingDecisionTasks
    - DeprecateActivityType
    - DeprecateDomain
    - DeprecateWorkflowType
    - DescribeActivityType
    - DescribeDomain
    - DescribeWorkflowExecution
    - DescribeWorkflowType
    - GetWorkflowExecutionHistory
    - ListActivityTypes
    - ListClosedWorkflowExecutions
    - ListDomains
    - ListOpenWorkflowExecutions
    - ListWorkflowTypes
    - PollForActivityTask
    - PollForDecisionTask
    - RecordActivityTaskHeartbeat
    - RegisterActivityType
    - RegisterDomain
    - RegisterWorkflowType
    - RequestCancelWorkflowExecution
    - RespondActivityTaskCanceled
    - RespondActivityTaskCompleted
    - RespondActivityTaskFailed
    - RespondDecisionTaskCompleted
    - SignalWorkflowExecution
    - StartWorkflowExecution
    - TerminateWorkflowExecution
